# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

link_with ['Draw Everything']

inhibit_all_warnings!

pod 'AFNetworking', '2.5.0'
pod 'iCarousel', '1.8.1'
pod 'Google-AdMob-Ads-SDK', '6.12.2'
pod 'RZSquaresLoading', '1.1'

